import type { ChatMessage, Conversation, ConversationType, PendingAttachment } from '~/types/chat'
const conversations = reactive<Record<ConversationType, Conversation[]>>({ post: [], campaign: [] })
const messages = reactive<Record<string, ChatMessage[]>>({})
const attachments = ref<PendingAttachment[]>([])
export function useChatWorkspace(type: ConversationType) {
  const config = useRuntimeConfig(); const section = type === 'post' ? 'posts' : 'campaigns'
  const busy = ref(false); const error = ref<string | null>(null)
  function headers(): Record<string, string> { if (!import.meta.client) return {}; const user = localStorage.getItem('promotiva-user-id') || crypto.randomUUID(); const project = localStorage.getItem('promotiva-project-id') || crypto.randomUUID(); localStorage.setItem('promotiva-user-id', user); localStorage.setItem('promotiva-project-id', project); return { 'X-User-ID': user, 'X-Project-ID': project } }
  async function request<T>(url: string, options: { method?: string; body?: unknown } = {}): Promise<T> { const isForm = options.body instanceof FormData; let body: BodyInit | undefined; if (isForm) body = options.body as FormData; else if (options.body != null) body = JSON.stringify(options.body); let response: Response; try { response = await fetch(url, { method: options.method || 'GET', headers: { ...headers(), ...(isForm ? {} : { 'Content-Type': 'application/json' }) }, body }) } catch { throw new Error('Cannot connect to the Promotiva API. Start the backend on port 8000 and try again.') } if (!response.ok) { const detail = await response.text(); throw new Error(detail || `Request failed (${response.status})`) } return await response.json() as T }
  async function loadConversations() { try { conversations[type] = await request(`${config.public.apiBaseUrl}/${section}/conversations`) } catch (cause) { error.value = cause instanceof Error ? cause.message : 'Could not load chats.' } }
  async function createConversation(title: string) { const item = await request<Conversation>(`${config.public.apiBaseUrl}/${section}/conversations`, { method: 'POST', body: { title, type } }); conversations[type] = [item, ...conversations[type]]; return item }
  async function loadConversation(id: string) { const item = await request<Conversation>(`${config.public.apiBaseUrl}/${section}/conversations/${id}`); if (item.type !== type) throw new Error('Conversation belongs to another workspace'); const page = await request<{ items: ChatMessage[] }>(`${config.public.apiBaseUrl}/${section}/conversations/${id}/messages`); messages[id] = page.items }
  async function send(id: string, content: string) { busy.value = true; error.value = null; try { let message: ChatMessage; if (type === 'post') { const turn = await request<{ user: ChatMessage; assistant: ChatMessage }>(`${config.public.apiBaseUrl}/${section}/conversations/${id}/turns`, { method: 'POST', body: { content, role: 'user', metadata: {} } }); message = turn.user; messages[id] = [...(messages[id] || []), turn.user, turn.assistant] } else { message = await request<ChatMessage>(`${config.public.apiBaseUrl}/${section}/conversations/${id}/messages`, { method: 'POST', body: { content, role: 'user', metadata: {} } }); messages[id] = [...(messages[id] || []), message] } for (const item of attachments.value) { const body = new FormData(); body.append('message_id', message.id); body.append('role', 'reference'); body.append('file', item.file); await request(`${config.public.apiBaseUrl}/assets`, { method: 'POST', body }) } clearAttachments(); return message } catch (cause) { error.value = cause instanceof Error ? cause.message : 'Message failed.'; throw cause } finally { busy.value = false } }
  function addFiles(files: FileList | null) { for (const file of Array.from(files || [])) if (file.type.startsWith('image/')) attachments.value.push({ id: crypto.randomUUID(), file, previewUrl: URL.createObjectURL(file) }) }
  function removeAttachment(id: string) { const item = attachments.value.find(x => x.id === id); if (item) URL.revokeObjectURL(item.previewUrl); attachments.value = attachments.value.filter(x => x.id !== id) }
  function clearAttachments() { attachments.value.forEach(x => URL.revokeObjectURL(x.previewUrl)); attachments.value = [] }
  return { conversations: computed(() => conversations[type]), messages, attachments, busy, error, loadConversations, createConversation, loadConversation, send, addFiles, removeAttachment, request }
}
