"""Tools that edit a customer's own assets without redrawing them."""

from .preservation import (
    PROTECTED_ROLES,
    BackgroundRemovalTool,
    CropTool,
    EdgeCleanupTool,
    EditOperation,
    EditStep,
    LightingAdaptationTool,
    MaskingTool,
    PerspectiveDirective,
    PerspectiveMode,
    PerspectiveTool,
    PreservationError,
    PreservationFailure,
    PreservationInput,
    PreservedAssetResult,
    ProductPreservationPipeline,
    ScalePlacementTool,
    ShadowDirective,
    ShadowIntegrationTool,
)

__all__ = [
    "PROTECTED_ROLES",
    "BackgroundRemovalTool",
    "CropTool",
    "EdgeCleanupTool",
    "EditOperation",
    "EditStep",
    "LightingAdaptationTool",
    "MaskingTool",
    "PerspectiveDirective",
    "PerspectiveMode",
    "PerspectiveTool",
    "PreservationError",
    "PreservationFailure",
    "PreservationInput",
    "PreservedAssetResult",
    "ProductPreservationPipeline",
    "ScalePlacementTool",
    "ShadowDirective",
    "ShadowIntegrationTool",
]
